-- Drops für die Tabellen
-- @author Pavic Antonio

DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Spieler CASCADE;
DROP TABLE IF EXISTS Standort CASCADE;
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Angestellter CASCADE;
DROP TABLE IF EXISTS Mannschaft CASCADE;
DROP TABLE IF EXISTS Mitglied CASCADE;
DROP TABLE IF EXISTS Spiel CASCADE;
DROP TABLE IF EXISTS Spieltin CASCADE;
DROP TABLE IF EXISTS Fanclub CASCADE;
DROP TABLE IF EXISTS Betreuen CASCADE;
